# Makefile for UCLA ROMS tools on Stanford's Sherlock cluster
#========== ======= =========== ======== === ==== =====
# This makefile requires that you have the following 
# environment variables defined: 
#  ROMS_ROOT, NETCDF_ROOT, FCOMP

#
.SUFFIXES: .o .f .F .f90


.F.o:
	@$(CPP) -P $*.F | mpc > $*.f
	$(FCOMP) -c $(FFLAGS) -o $*.o $*.f $(INCS)
	@/bin/rm -f $*.f
.F.f:
	$(CPP) -P  $*.F | mpc > $*.f
.f.o:
	$(FCOMP) -c $(FFLAGS) -o $*.o $*.f $(INCS)
.f90.o:
	$(FCOMP) -c $(FFLAGS) -o $*.o $*.f90 $(INCS)

     CPP = cpp -traditional

# Path of NetCDF library

	NETCDF_INC = -I$(NETCDF_ROOT)/include
	NETCDF_LIB = -L$(NETCDF_ROOT)/lib -lnetcdff

	INCS = $(NETCDF_INC)
	LIBS = $(NETCDF_LIB)

# Fortran compiler options/flags
	FFLAGS = -O3 -flto -ffast-math

# --------------------------------------------------------------------

ALL = partit ncjoin ncjoin_mpi extract_data_join nc3to4z zslice sample
#r2r_bry r2r_match_topo r2r_init

all:	$(info MAKING ROMS TOOLS:) mpc $(ALL)

#install: $(ALL)
#	mv $(ALL) ~/bin

# Note: the following .f: dependencies are needed to make everything
# go through CPP and take custom defined CPPFLAGS rather than compiling
# executables from .F directly.

chkindent: chkindent.f

# The following two are built from the same source
# and differ only CPP macro setting:

mreplace.f: mreplace.F
	$(CPP) -P $(CPPFLAGS) -DREPLACE mreplace.F > mreplace.f
	
partit: partit.o insert_node.o lenstr.o
	$(FCOMP) $(FFLAGS) $(LDFLAGS) -o partit partit.o insert_node.o lenstr.o $(LIBS)

ncjoin: ncjoin.o lenstr.o
	$(FCOMP) $(FFLAGS) $(LDFLAGS) -o ncjoin ncjoin.o lenstr.o $(LIBS)	

simple_xy_par_wr: simple_xy_par_wr.o
	$(FCOMP) $(FFLAGS) $(LDFLAGS) -o simple_xy_par_wr simple_xy_par_wr.o $(LIBS)	
	
ncjoin_mpi: ncjoin_mpi.opt ncjoin_mod.o ncjoin_mpi.o lenstr.o
	$(FCOMP) $(FFLAGS) $(LDFLAGS) -o ncjoin_mpi ncjoin_mod.o ncjoin_mpi.o lenstr.o $(LIBS)
	
nc3to4z: nc3to4z.o lenstr.o read_string.o
	$(FCOMP) $(FFLAGS) $(LDFLAGS) -o nc3to4z nc3to4z.o lenstr.o read_string.o $(LIBS)
	
mpc: mpc.F Makefile
	$(CPP) $(CPPFLAGS) -P mpc.F > ./mpc.f
	$(FCOMP) $(FFLAGS) $(LDFLAGS) -o mpc ./mpc.f
	
extract_data_join: ncjoin_mod.o extract_data_join.o  lenstr.o
	$(FCOMP) $(FFLAGS) $(LDFLAGS) -o extract_data_join ncjoin_mod.o extract_data_join.o lenstr.o  $(LIBS)
	
particle_join: ncjoin_mod.o particle_join.o  lenstr.o
	$(FCOMP) $(FFLAGS) $(LDFLAGS) -o particle_join ncjoin_mod.o particle_join.o lenstr.o  $(LIBS)

R2R_INIT = r2r_init.o r2r_interp_init.o r2r_subs.o r2r_rotate.o r2r_vert_interp.o\
           set_depth.o etch_into_land.o spln2d.o tiling.o roms_read_write.o\
           read_string.o lenstr.o

r2r_init: $(R2R_INIT)
	$(FCOMP) $(FFLAGS) $(LDFLAGS) -o r2r_init $(R2R_INIT) $(LIBS)

 R2R_BRY = r2r_bry.o r2r_bry_interp.o r2r_subs.o r2r_bry_rotate.o r2r_rotate.o\
           r2r_vert_interp.o set_depth.o etch_into_land.o spln2d.o tiling.o\
           def_bry_file.o roms_read_write.o read_string.o lenstr.o

r2r_bry: $(R2R_BRY)
	$(FCOMP) $(FFLAGS) $(LDFLAGS) -o r2r_bry $(R2R_BRY) $(LIBS)

 ZSLICE = zslice.o set_depth.o sigma_to_z_intr.o read_add_write.o\
	  roms_read_write.o read_string.o lenstr.o tiling.o

 IPSLICE = ipslice.o set_depth.o sigma_to_z_intr.o rho_eos.o\
	   read_add_write.o roms_read_write.o read_string.o lenstr.o tiling.o

 SAMPLE = roms_read_write.o sample.o tiling.o\
          read_add_write.o read_string.o lenstr.o

R2R_MATCH_TOPO = r2r_match_topo.o r2r_interp_init.o mrg_zone_subs.o tiling.o\
                        spln2d.o roms_read_write.o read_string.o lenstr.o
                        
r2r_match_topo: $(R2R_MATCH_TOPO)
	$(FCOMP) $(FFLAGS) $(LDFLAGS) -o r2r_match_topo $(R2R_MATCH_TOPO) $(LIBS)                                  
          
zslice: $(ZSLICE)
	$(FCOMP) $(FFLAGS) -o zslice $(ZSLICE) $(LIBS)

ipslice: $(IPSLICE)
	$(FCOMP) $(FFLAGS) -o ipslice $(IPSLICE) $(LIBS)

ipslice.f: zslice.F
	$(CPP) -P $(CPPFLAGS) -DIPSLICE zslice.F | ./mpc > ipslice.f

sample: $(SAMPLE)
	$(FCOMP) $(FFLAGS) -o sample $(SAMPLE) $(LIBS)

clean:
	/bin/rm -f *.f *.o *.a *.s *.trace *.mod

clobber: clean
	/bin/rm -f $(ALL) *.bak
	
include Make.depend
