# Makefile for UCLA ROMS tools on Stanford's Sherlock cluster
#========== ======= =========== ======== === ==== =====
# This makefile requires that you have the following 
# environment variables defined: 
#  ROMS_ROOT, NETCDF_ROOT, NETCDFC_ROOT, FCOMP

#
.SUFFIXES: .o .f .F .f90

.F.o:
	@$(CPP) -P $*.F | mpc > $*.f
	$(FCOMP) -c $(FFLAGS) -o $*.o $*.f $(INCS)
	@/bin/rm -f $*.f
.F.f:
	$(CPP) -P  $*.F | mpc > $*.f
.f.o:
	$(FCOMP) -c $(FFLAGS) -o $*.o $*.f $(INCS)

     CPP = cpp -traditional

# Pathd to NetCDF libraries:

	NETCDF_INC = -I$(NETCDF_ROOT)/include
	NETCDF_LIB = -L$(NETCDF_ROOT)/lib -lnetcdff
	NETCDFC_LIB = -L$(NETCDFC_ROOT)/lib -lnetcdf

	INCS = $(NETCDF_INC)
	LIBS = $(NETCDF_LIB) $(NETCDFC_LIB)

# Fortran compiler options/flags:
	FFLAGS = -O3 -flto -ffast-math

PSRC = partit.F roms_part.F nc_read_write.F
MSRC = partmap.F roms_part.F nc_read_write.F
OSRC = optimal_part.F roms_part.F nc_read_write.F
JSRC = ncjoin.F roms_part.F nc_read_write.F

  PCS = $(PSRC:.F=.f)
  PBJS = $(PSRC:.F=.o) 
  MCS = $(MSRC:.F=.f)
  MBJS = $(MSRC:.F=.o) 
  OCS = $(OSRC:.F=.f)
  OBJS = $(OSRC:.F=.o) 
  JCS = $(JSRC:.F=.f)
  JBJS = $(JSRC:.F=.o) 

# Everything
all: depend partit partmap optimal ncjoin 

partit:  $(PBJS)
	@echo 'Making: $(PBJS)'
	$(FCOMP) $(FFLAGS) $(LDFLAGS) -o partit $(PBJS) $(LIBS)

partmap:  $(MBJS)
	@echo 'Making: $(MBJS)'
	$(FCOMP) $(FFLAGS) $(LDFLAGS) -o partmap $(MBJS) $(LIBS)

optimal:  $(OBJS)
	@echo 'Making: $(OBJS)'
	$(FCOMP) $(FFLAGS) $(LDFLAGS) -o optimal $(OBJS) $(LIBS)

ncjoin:  $(JBJS)
	@echo 'Making: $(JBJS)'
	$(FCOMP) $(FFLAGS) $(LDFLAGS) -o ncjoin $(JBJS) $(LIBS)

depend:  # Note: cross_matrix no longer used
	@makedepf90 $(PSRC) $(MSRC) $(OSRC) $(JSRC) > Make.depend
	@echo 'Updated Make.depend (dependency list)'

# Cleaning targets
# -------- -------
clean:
	/bin/rm -rf *.f *.o *.a *.s *.mod *.trace *~ partit partmap optimal ncjoin 

# Automatically generated dependency list:

include Make.depend

